routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',             'Guest\HomeController@index')->name('guest.home');
Route::get('/test',         'Guest\HomeController@test');
Route::get('/phpinfo',      'Guest\HomeController@phpinfo');
// Route::get('/curl',         'Guest\HomeController@curl')->name('curl');
Route::get('/tentang-kami', 'Guest\HomeController@tentangkami')->name('guest.tentang');
Route::get('/hubungi-kami', 'Guest\HomeController@hubungikami')->name('guest.hubungi');
Route::get('/home',         'Guest\HomeController@checkrole')->name('guest.checkrole');

//EMAIL
Route::get('/mail/tes',                         'MailController@test')->name('mail');
Route::get('/mail/verify-email',                'MailController@verifyRegistration')->name('email.verification');
Route::get('/mail/verify-resend/{username}',    'MailController@resendVerification')->name('email.verification.resend');

Route::get('/dummy/simulasi/peserta',        'DummyController@dummySimulasiPeserta')->name('dummy.simulasi.peserta');

/*--------------------------------------------------------------------------
AUTH
-------------------------------------------------------------------------*/
Route::get('/login',        'Auth\LoginController@loginForm')->name('auth.login');
Route::post('/login',       'Auth\LoginController@login')->name('auth.login.post');
Route::post('/loginWithGoogle', 'Auth\LoginController@loginWithGoogle')->name('auth.login.with.google');
Route::get('/login-admin',  'Auth\LoginController@loginAdminForm')->name('auth.login.admin');
Route::post('/login-admin', 'Auth\LoginController@loginAdmin')->name('auth.login.admin.post');
Route::get('/logout',       'Auth\LoginController@logout')->name('auth.logout');
Route::get('/register',     'Auth\RegisterController@registerForm')->name('auth.register');
Route::post('/register',    'Auth\RegisterController@register')->name('auth.register.post');


/*--------------------------------------------------------------------------
RESET PASSWORD
-------------------------------------------------------------------------*/
Route::get('password/reset',        'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.forgot');
Route::post('password/email',       'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.email');
Route::get('password/reset/{token}','Auth\ResetPasswordController@showResetForm')->name('auth.password.reset.form');
Route::post('password/reset',       'Auth\ResetPasswordController@reset')->name('auth.password.reset.save');


/*--------------------------------------------------------------------------
SUPER ADMIN
-------------------------------------------------------------------------*/
Route::group(['middleware' => 'superadmin', 'prefix' => 'superadmin'], function(){
    Route::get('/', 'SuperAdmin\HomeController@index')->name('superadmin');

    Route::group(['prefix' => 'user'], function(){
        Route::get('/',                 'SuperAdmin\UserController@index')->name('superadmin.user');
        Route::get('/export',           'SuperAdmin\UserController@export')->name('superadmin.user.export');
        Route::post('/tambah',          'SuperAdmin\UserController@tambahPost')->name('superadmin.user.tambah.post');
        Route::post('/ubah/{idUser}',   'SuperAdmin\UserController@ubahPost')->name('superadmin.user.ubah.post');
        Route::get('/get/{idUser}',     'SuperAdmin\UserController@getUser')->name('superadmin.user.get');
        Route::get('/hapus/{idUser}',   'SuperAdmin\UserController@hapus')->name('superadmin.user.hapus');
    });

});


/*--------------------------------------------------------------------------
ALL ADMIN
-------------------------------------------------------------------------*/
Route::group(['middleware' => 'alladmin', 'prefix' => 'admin'], function(){
    Route::group(['prefix' => 'profil'], function(){
        Route::get('/edit',             'Admin\ProfilController@edit')->name('alladmin.profil.edit');
        Route::post('/edit-profil',     'Admin\ProfilController@editProfil')->name('alladmin.profil.edit.profil');
        Route::post('/edit-email',      'Admin\ProfilController@editEmail')->name('alladmin.profil.edit.email');
        Route::post('/edit-username',   'Admin\ProfilController@editUsername')->name('alladmin.profil.edit.username');
        Route::post('/edit-password',   'Admin\ProfilController@editPassword')->name('alladmin.profil.edit.password');
        Route::get('/photo',            'Admin\ProfilController@photo')->name('alladmin.profil.photo');
        Route::post('/photo',           'Admin\ProfilController@uploadPhoto')->name('alladmin.profil.photo.post');
    });
});


/*--------------------------------------------------------------------------
ADMIN GENERAL
-------------------------------------------------------------------------*/
Route::group(['middleware' => 'admin', 'prefix' => 'admin'], function(){
    Route::get('/', 'Admin\HomeController@index')->name('admin');

    Route::group(['prefix' => 'grupchat'], function(){
        Route::get('/',                 'Admin\GrupChatController@index')->name('admin.grupchat');
        Route::get('/view/{id}',        'Admin\GrupChatController@viewGrup')->name('admin.grupchat.view');
        Route::get('/tambah',           'Admin\GrupChatController@formTambah')->name('admin.grupchat.tambah');
        Route::post('/tambah',          'Admin\GrupChatController@prosesTambah')->name('admin.grupchat.tambah.post');
        Route::get('/edit/{id}',        'Admin\GrupChatController@formEdit')->name('admin.grupchat.edit');
        Route::post('/edit/{id}',       'Admin\GrupChatController@prosesEdit')->name('admin.grupchat.edit.post');
        Route::get('/delete/{id}',      'Admin\GrupChatController@delete')->name('admin.grupchat.delete');
        Route::get('/member/kick/{id}', 'Admin\GrupChatController@kick')->name('admin.grupchat.member.kick');
    });

    Route::group(['prefix' => 'informasi'], function(){
        Route::get('/',             'Admin\InformasiController@index')->name('admin.informasi');
        Route::get('/form/{id?}',   'Admin\InformasiController@formInformasi')->name('admin.informasi.form');
        Route::post('/form/{id?}',  'Admin\InformasiController@saveInformasi')->name('admin.informasi.save');
        Route::get('/delete/{id}',  'Admin\InformasiController@delete')->name('admin.informasi.delete');
    });

    Route::group(['prefix' => 'passinggrade'], function(){
        Route::get('/',                                 'Admin\PassingGradeController@index')->name('admin.passgrade');
        Route::get('/formuniv/{id?}',                   'Admin\PassingGradeController@formUniv')->name('admin.passgrade.form.univ');
        Route::post('/saveuniv/{id?}',                  'Admin\PassingGradeController@saveUniv')->name('admin.passgrade.save.univ');
        Route::get('/openuniv/{id}',                    'Admin\PassingGradeController@openUniv')->name('admin.passgrade.open.univ');
        Route::get('/deluniv/{id}',                     'Admin\PassingGradeController@deleteUniv')->name('admin.passgrade.delete.univ');
        Route::get('/openuniv/{id}/deljur/{idJur}',     'Admin\PassingGradeController@deleteJurusan')->name('admin.passgrade.delete.jurusan');
        Route::get('/openuniv/{id}/formjur/{idJur?}',   'Admin\PassingGradeController@formJurusan')->name('admin.passgrade.form.jurusan');
        Route::post('/openuniv/{id}/savejur/{idJur?}',  'Admin\PassingGradeController@saveJurusan')->name('admin.passgrade.save.jurusan');
    });

    Route::group(['prefix' => 'sekolah'], function(){
        Route::get('/',             'Admin\SekolahController@index')->name('admin.sekolah');
        Route::get('/unchecked',    'Admin\SekolahController@unchecked')->name('admin.sekolah.unchecked');
        Route::get('/tambah',       'Admin\SekolahController@tambahForm')->name('admin.sekolah.tambah');
        Route::post('/tambah',      'Admin\SekolahController@tambahPost')->name('admin.sekolah.tambah.post');
        Route::get('/delete/{id}',  'Admin\SekolahController@delete')->name('admin.sekolah.delete');
        Route::get('/edit/{id}',    'Admin\SekolahController@editForm')->name('admin.sekolah.edit');
        Route::post('/edit/{id}',   'Admin\SekolahController@editPost')->name('admin.sekolah.edit.post');
    });

    Route::group(['prefix' => 'member'], function(){
        Route::get('/',                 'Admin\MemberController@index')->name('admin.member');
        Route::get('/provinsi/{id?}',   'Admin\MemberController@provinsi')->name('admin.member.provinsi');
        Route::get('/generate',         'Admin\MemberController@generate')->name('admin.member.generate');
    });

});


/*--------------------------------------------------------------------------
ADMIN UJIAN
-------------------------------------------------------------------------*/
Route::group(['middleware' => 'adminujian', 'prefix' => 'adminujian'], function(){
    Route::get('/', 'AdminUjian\HomeController@index')->name('adminujian');

    Route::group(['prefix' => 'ujian'], function(){
        Route::get('/',                     'AdminUjian\UjianController@index')->name('admin.ujian.soal');
        Route::get('/tambah',          'AdminUjian\UjianController@formTambahUjian')->name('admin.ujian.soal.tambah');
        Route::post('/tambah',         'AdminUjian\UjianController@prosesTambahUjian')->name('admin.ujian.soal.tambah.post');
        Route::group(['prefix' => '{id}'], function(){
            Route::get('/',                         'AdminUjian\UjianController@kelolaSoal')->name('admin.ujian.soal.kelola');

app/Models/Universitas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Universitas extends Model {
    use SoftDeletes;
    protected $table        = 'tbl_universitas';
    protected $primaryKey   = 'id';
    protected $keyType      = 'string';
    public $incrementing    = false;
    protected $dates        = ['deleted_at'];

    protected static function boot() {
        parent::boot();
        static::deleting(function($data) {
            // $data->tiket()->delete();
        });
    }

    //RELATION table
    public function jurusan() {
        return $this->hasMany('App\Models\Jurusan', 'id_universitas');
    }
    public function getNamaAttribute($value) {
        return strtoupper($value);
    }
}

resources/views/template/borang.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title></title>
    <style>
    @page {
        margin: 1.5cm;
    }
    body { font-size: 13px; }
    h1 { font-size: 30px; margin-bottom: 1cm; }
    .page-break {
        page-break-after: always;
    }
    .text-center { text-align: center; }
    .text-right { text-align: right; }
    table.borang td { padding: 5px; }
    .box { border: 1px solid #333; padding: 3px; }
    .box.peringkat { width: 100px; height: 100px; float: right; text-align: center; }
    .text-peringkat { font-size: 50px; font-weight: bold; margin-top: 10px; display: block;}
</style>
</head>
<body>
    @foreach($peserta as $index => $data)
    <h1 class="text-center">BORANG LAPORAN REKOMENDASI</h1>
    <table class="borang" width="17cm">
        <tr>
            <td width="170px">Nama</td>
            <td width="5px">:</td>
            <td colspan="2">{{ $data->profil->nama }}</td>
            <td rowspan="4" class="text-center">
                <div class="box peringkat">
                    PERINGKAT <br>
                    <span class="text-peringkat">{{ $data->peringkat }}</span>
                </div>
            </td>
        </tr>
        <tr>
            <td width="170px">No Ujian</td>
            <td>:</td>
            <td colspan="2">{{ $data->no_peserta }}</td>
        </tr>
        <tr>
            <td width="170px">Asal Sekolah</td>
            <td>:</td>
            <td colspan="2">{{ $data->profil->id_sekolah != null ? $data->profil->sekolah->nama : "-"  }}</td>
        </tr>
        <tr>
            <td width="170px">Jurusan Ujian</td>
            <td>:</td>
            <td colspan="2">{{ $data->mapel->nama }}</td>
        </tr>
        <tr>
            <td width="170px">Hasil Ujian</td>
            <td>:</td>
            <td>{{ $data->nilai_akhir }}</td>
        </tr>
        <tr>
            <td colspan="3">
                <div class="box">
                    <table width="100%">
                        <tr>
                            <td class="50%">BENAR: {{ $data->jumlah_benar }}</td>
                            <td class="50%">SALAH/KOSONG: {{ $data->jumlah_salah + $data->jumlah_tidak_jawab }}</td>
                        </tr>
                    </table>
                </div>
            </td>
        </tr>
        <tr>
            <td width="170px">Soal Sulit</td>
            <td></td>
            <td colspan="3">
                <div class="box">
                    <?php $no =0; ?>
                    @foreach($data->koreksi->where("kriteria", "sulit") as $soal)
                        {{ $no == 0 ? $soal->no_soal : ", " . $soal->no_soal}}
                        <?php $no++; ?>
                    @endforeach
                </div>
            </td>
        </tr>
        <tr>
            <td width="170px">Soal Sedang</td>
            <td></td>
            <td colspan="3">
                <div class="box">
                    <?php $no =0; ?>
                    @foreach($data->koreksi->where("kriteria", "sedang") as $soal)
                        {{ $no == 0 ? $soal->no_soal : ", " . $soal->no_soal}}
                        <?php $no++; ?>
                    @endforeach
                </div>
            </td>
        </tr>
        <tr>
            <td width="170px">Soal Mudah</td>
            <td></td>
            <td colspan="3">
                <div class="box">
                    <?php $no =0; ?>
                    @foreach($data->koreksi->where("kriteria", "mudah") as $soal)
                        {{ $no == 0 ? $soal->no_soal : ", " . $soal->no_soal}}
                        <?php $no++; ?>
                    @endforeach
                </div>
            </td>
        </tr>
        <tr>
            <td width="170px">Pilihan Saat Simulasi</td>
            <td></td>
            <td>Pilihan 1</td>
        </tr>
        <tr>
            <td colspan="2"></td>
            <td colspan="2"><div class="box">{{ $data->passingGrade->pilihan1->universitas != null ? $data->passingGrade->pilihan1->universitas->nama : "-" }}</div></td>
        </tr>
        <tr>
            <td colspan="2"></td>
            <td colspan="2"><div class="box">{{ $data->passingGrade->pilihan1->universitas != null ? $data->passingGrade->pilihan1->jurusan : "-" }}</div></td>
        </tr>
        <tr>
            <td colspan="2"></td>
            <td>Pilihan 2</td>
        </tr>
        <tr>
            <td colspan="2"></td>
            <td colspan="2"><div class="box">{{ $data->passingGrade->pilihan2->universitas != null ? $data->passingGrade->pilihan2->universitas->nama : "-" }}</div></td>
        </tr>
        <tr>
            <td colspan="2"></td>
            <td colspan="2"><div class="box">{{ $data->passingGrade->pilihan2->universitas != null ? $data->passingGrade->pilihan2->jurusan : "-" }}</div></td>
        </tr>
        <tr>
            <td colspan="2"></td>
            <td>Pilihan 3</td>
        </tr>
        <tr>
            <td colspan="2"></td>
            <td colspan="2"><div class="box">{{ $data->passingGrade->pilihan3->universitas != null ? $data->passingGrade->pilihan3->universitas->nama : "-" }}</div></td>
        </tr>
        <tr>
            <td colspan="2"></td>
            <td colspan="2"><div class="box">{{ $data->passingGrade->pilihan3->universitas != null ? $data->passingGrade->pilihan3->jurusan : "-" }}</div></td>
        </tr>
        <tr valign="top">
            <td width="170px">Keterangan</td>
            <td></td>
            <td colspan="3"><div class="box">{{ $data->id_passing_grade_lolos == null ? "Anda Tidak Lulus" : "Lulus di " . strtoupper($data->passingGradeLolos->jurusan) . " " . strtoupper($data->passingGradeLolos->universitas->nama) }}</div></td>
        </tr>
        <tr valign="top">
            <td width="170px">Rekomendasi Konsultasi</td>
            <td></td>
            <td colspan="3"><textarea class="box" style="height: 60px"></textarea></td>
        </tr>
        <tr valign="top">
            <td colspan="2"></td>
            <td colspan="3" class="text-right">Bandar Lampung, {{ tanggal(date("Y-m-d")) }}</td>
        </tr>
        <tr valign="top">
            <td colspan="2"></td>
            <td colspan="2"></td>
        </tr>
        <tr valign="top">
            <td colspan="2"></td>
            <td colspan="3" class="text-right">
                <div class="" style="margin-top: 2cm">
                    (________________________________)
                </div>
            </td>
        </tr>
    </table>
    @if($index+1 < $peserta->count())
    <div class="page-break"></div>
    @endif
    @endforeach
</body>
</html>

resources/views/template/download-data-member.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{{ asset('img/logo.png') }}">
    <title>@yield('title') - Baristand</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <style media="screen">
    tr td, tr th{
        padding: 10px !important;
        margin: 0 !important;
    }
</style>
<script src="{{ asset('asset-beagle/lib/jquery/jquery.min.js') }}" type="text/javascript"></script>
</head>
<!-- END HEAD -->

<body style="background: white">
    <h1 class="text-center" style="margin-top: 50px;">
        DATA MEMBER SANEDU
    </h1>
    <div class="text-center" style="margin-bottom: 20px;">{{ hariTanggalWaktu() }}</div>
    <table class="table table-bordered" style="font-weight: normal;">
        <thead>
            <tr>
                <th>No</th>
                <th>Nama</th>
                <th>Sekolah</th>
                <th>No. Telp</th>
                <th>Point</th>
            </tr>
        </thead>
        <tbody>
            @foreach($member as $no => $val)
            <tr>
                <td>{{ $no+1 }}</td>
                <td>{{ $val->nama }}</td>
                <td>{{ $val->sekolah }}</td>
                <td>{{ $val->no_hp }}</td>
                <td></td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <th>No</th>
                <th>Nama</th>
                <th>Sekolah</th>
                <th>No. Telp</th>
                <th>Point</th>
            </tr>
        </tfoot>
    </table>
</body>
</html>

resources/views/template/kartuujian.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>TANDA BUKTI PEMBAYARAN</title>
    <style media="screen">
    @page {
        margin: 0;
    }
    body {
        font-family: helvetica;
        margin: 0;
        padding: 0;
    }
    .col {
        width: 100%;
    }
    .wrapper {
        border: 2px dashed #BBB;
        box-sizing: border-box;
        margin: 10px;
        padding: 10px;
        overflow: hidden;
    }
    header {
        border: 1px solid #AAA;
        padding: 7px;
        overflow: hidden;
        margin-bottom: 10px;
        clear: both;
    }
    header * {
        display: inline-block;
    }
    header img {
        width: 50px;
        margin-left: 10px;
        box-sizing: border-box;
    }
    header h1 {
        width: 400px;
        box-sizing: border-box;
        padding: 5px;
        font-size: 22px;
        text-align: center;
        margin: 0;
        color: #333;
        font-family: helvetica;
        font-weight: 600;
    }

    .box {
        border: 1px solid #AAA;
        padding: 10px;
        margin-bottom: 10px;
    }

    .pengumuman {
        font-size: 14px;
    }

    .text-center {
        text-align: center;
    }
    .text-red {
        color: red;
    }

    table.alamat td, table.alamat th {
        vertical-align: top;
        text-align: left;
        font-family: helvetica;
        font-size: 16px;
    }

    table.lokasi-ujian td, table.alamat th {
        vertical-align: top;
        text-align: left;
        font-family: helvetica;
        font-size: 13px;
        font-weight: bold;
    }

    .qrcode {
        margin: 0 auto;
        text-align: center;
    }
    .qrcode img {
        height: 93px;
    }
    .text {
        font-weight: 400;
        font-size: 12px;
        margin: 5px 0 0 10px;
    }
    table.jadwal {
        width: 100%;
        box-sizing: border-box;
        border-spacing: 0;
    }
    table.jadwal td, table.jadwal th {
        border: 1px solid #EFEFEF;
        margin: 0;
        padding: 5px;
        font-size: 12px;
    }
    table.jadwal td {
        text-align: left;
    }
    table.jadwal td.text-center {
        text-align: center;
    }
    table.ttd {
        width: 100%;
        margin-top: 15px;
    }
    table.ttd th {
        text-align: left;
        font-weight: bold;
        font-size: 12px;
    }
    table.ttd td {
        border-bottom: 1px dashed #AAA;
    }


    .perlengkapan {
        font-weight: bold;
    }
    .title-box {
        font-weight: bold;
        font-size: 14px;
        margin: 0;
    }
    .perlengkapan ul {
        font-size: 14px;
        margin: 5px 0;
    }
    .perlengkapan ul li {
        list-style: square;
    }

    table.isi-alamat {
        font-size: 14px;
        margin: 10px;
        width: 100%;
        box-sizing: border-box;
    }
    table.isi-alamat tr td ~ td {
        border-bottom: 1px solid #AAA;
        padding: 5px;
        height: 16px;
    }

    ul.prodi {
        font-weight: bold;
        margin: 5px;
    }
    ul.prodi li {
        list-style: none;
        margin: 0;
    }
    ul.prodi strong {
        display: block;
    }
    ul.prodi span {
        font-weight: normal;
        display: block;
        box-sizing: border-box;
        margin-left: 10px;
    }

    #table-main {
        width: 1120px;
    }
    #table-main tr td.column {
        width: 50%;
        vertical-align: top;
    }
    </style>
</head>
<body>
    <div class="body">
        <table id="table-main">
            <tr>
                <td class="column">
                    <div class="col">
                        <div class="wrapper">
                            <header style="padding-top: 25px">
                                <img src="{{ asset('asset-beagle/img/logo-san.png')}}" alt="">
                                <h1>TANDA BUKTI PENDAFTARAN SIMULASI SBMPTN</h1>
                            </header>
                            <div class="box">
                                <table class="alamat">
                                    <tr>
                                        <th>NOMOR PESERTA </th>
                                        <th> : {{ $peserta->no_peserta }}</th>
                                    </tr>
                                    <tr>
                                        <th>NAMA PESERTA </th>
                                        <th> : {{ $peserta->profil->nama }}</th>
                                    </tr>
                                    <tr>
                                        <th>KELOMPOK UJIAN </th>
                                        <th> : {{ $peserta->mapel->nama }}</th>
                                    </tr>
                                </table>
                            </div>
                            <div class="box">
                                <table class="alamat">
                                    <tr>
                                        <td>ALAMAT : </td>
                                        <td>
                                            {{ $peserta->profil->alamat }}
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="box text-center pengumuman" style="font-size: 19px;">
                                TRY OUT SIMULASI SBMPTN SANEDU AKAN DILAKSANKAN <br>
                                <strong class="text-red">{{ strtoupper(tanggal($peserta->simulasi->tanggal_pelaksanaan)) }}</strong>
                            </div>
                            <div class="box text-center pengumuman" style="font-size: 16px;">
                                PENGUMUMAN DILIHAT MELALUI WEBSITE PENDAFTARAN SANEDU.ID <br>
                                <strong class="text-red">{{ strtoupper(tanggal($peserta->simulasi->tanggal_pengumuman)) }}</strong>
                            </div>
                            <div class="box text-center">
                                <table class="jadwal">
                                    <tr>
                                        <th width="100px">Waktu</th>
                                        <th>Tempat</th>
                                        <th>Kegiatan</th>
                                    </tr>
                                    @foreach($peserta->simulasi->agenda as $agenda)
                                    <tr>
                                        <td class="text-center">{{ jamMenit($agenda->waktu_mulai) }} - {{ jamMenit($agenda->waktu_selesai) }}</td>
                                        <td>{{ $agenda->tempat }}</td>
                                        <td>{{ $agenda->nama_agenda }}</td>
                                    </tr>
                                    @endforeach
                                </table>
                            </div>
                        </div>
                    </div>
                </td>
                <td class="column">
                    <div class="col">
                        <div class="wrapper">
                            <div class="box">
                                <p class="title-box">ALAMAT PADA SAAT MENGIKUTI UJIAN (HARUS DIISI)</p>
                                <table class="isi-alamat">
                                    <tr>
                                        <th width="20px;">ALAMAT</th>
                                        <td width="2px;">:</td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <th></th>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <th>TELPON</th>
                                        <td>:</td>
                                        <td></td>
                                    </tr>
                                </table>
                            </div>
                            <div class="box perlengkapan">
                                <p class="title-box">PILIHAN PROGRAM STUDI : </p>
                                <ul class="prodi">
                                    <li>
                                        <strong>{{ $peserta->passingGrade->pilihan1->universitas != null ? $peserta->passingGrade->pilihan1->universitas->nama : "-" }}</strong>
                                        <span>{{ $peserta->passingGrade->pilihan1->universitas != null ? $peserta->passingGrade->pilihan1->jurusan : "-" }}</span>
                                    </li>
                                    <li>
                                        <strong>{{ $peserta->passingGrade->pilihan2->universitas != null ? $peserta->passingGrade->pilihan2->universitas->nama : "-" }}</strong>
                                        <span>{{ $peserta->passingGrade->pilihan2->universitas != null ? $peserta->passingGrade->pilihan2->jurusan : "-" }}</span>
                                    </li>
                                    <li>
                                        <strong>{{ $peserta->passingGrade->pilihan3->universitas != null ? $peserta->passingGrade->pilihan3->universitas->nama : "-" }}</strong>
                                        <span>{{ $peserta->passingGrade->pilihan3->universitas != null ? $peserta->passingGrade->pilihan3->jurusan : "-"}}</span>
                                    </li>
                                </ul>
                            </div>
                            <div class="box">
                                <p class="title-box">LOKASI UJIAN</p>
                                <table class="lokasi-ujian">
                                    <tr>
                                        <td>ALAMAT: {{ $peserta->ruang->nama }} - {{ $peserta->ruang->alamat }}</td>
                                    </tr>
                                </table>
                                <!-- <div class="qrcode">
                                    <img src="{{ asset('assets/img/qrcode.jpg') }}">
                                </div> -->
                                <p class="title-box" style="font-size: 12px;">LOKASI UJIAN TULIS BISA DILIHAT SATU HARI SEBELUM PELAKSANAAN UJIAN</p>
                            </div>
                            <div class="box perlengkapan">
                                <p class="title-box">PERNYATAAN</p>
                                <p class="text">DENGAN INI SAYA MENYATAKAN BAHWA DATA YANG SAYA ISIKAN DALAM BORANG PENDAFTARAN ONLINE SNMPTN JALUR UJIAN TERTULIS 2018 ADALAH BENAR. SAYA BERSEDIA MENERIMA SANKSI PEMBATALAN PENERIMAAN DI PTN YANG SAYA PILIH APABILA MELANGGAR PERNYATAAN INI.</p>
                                <table class="ttd">
                                    <tr>
                                        <th width="230px">TANDA TANGAN DAN NAMA TERANG : </th>
                                        <td></td>
                                    </tr>
                                </table>
                            </div>
                            <div class="box perlengkapan">
                                <p class="title-box">PERLENGKAPAN YANG HARUS DIBAWA PADA  SAAT UJIAN :</p>
                                <ul>
                                    <li>Kartu bukti pendaftaran ini</li>
                                    <li>Kartu identitas asli (Kartu Pelajar/KTP/SIM/Foto Raport atau yang lainnya)</li>
                                    <li>Pensil 2B secukupnya, karet penghapus, peraturan pensil (jika diperlukan)</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</body>
</html>